name: Java make jar
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:    
        ref: source
        repository: limdongsun0814/File-Utils
        token: ${{ secrets.GH_TOKEN }}
        # path: infra-study
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: make jar
      run: jar cvf com.file.utils.jar -C Utils .
    - name: Configure Git
      run: |
        git config --global user.email "asme12@naver.com"
        git config --global user.name "limdongsun0814"
    - name: git push
      run: |
        git fetch
        ls
        mv com.file.utils.jar /tmp/
        ls
        git checkout main
        rm com.file.utils.jar
        mv /tmp/com.file.utils.jar .
        ls
        git add com.file.utils.jar
        git commit -m "Add com.file.utils.jar"
        git push origin main     


      
